import Head from 'next/head'

import { Wrapper } from '@/components/common/wrapper/Wrapper'
import { Footer } from '@/components/footer/Footer'
import { Header } from '@/components/header/Header'
import { LevelCard } from '@/components/levelCard/LevelCard'
import style from '@/styles/LevelPage/levelPage.module.scss'

export default function LevelPage() {
  return (
    <>
      <Head>
        <title>LevelPage</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main>
        <Wrapper className={style.wrapper}>
          <LevelCard
            isRadio={false}
            title={'Level 1'}
            labels={['Confirm E-mail', 'Confirm Phone Number', 'Enter personal details']}
            subTitle={'Requirements'}
            signature={'Annual turnover - up to 2.500 EUR'}
            isChecked={true}
            theme={'colored'}
          />
          <LevelCard
            isRadio={true}
            title={'Level 2'}
            labels={['Upload Photo ID', 'Upload Utility Bill']}
            subTitle={'Requirements'}
            signature={'Annual turnover - up to 30.000 EUR'}
            isChecked={false}
            theme={'white'}
          />
        </Wrapper>
      </main>
      <Footer />
    </>
  )
}
